name: app_garagex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.2.5
  flutter_localizations:
    sdk: flutter
  intl: any

  flutter_pdfview: ^1.3.1
  shared_preferences: ^2.2.0
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.8

  google_maps_flutter: ^2.5.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0

  geolocator: ^14.0.0
  geocoding: ^3.0.0
  permission_handler: ^12.0.0+1

  table_calendar: ^3.0.9
  http: ^1.1.0

 
  dio: ^5.4.0             
  path_provider: ^2.1.1    
  open_file: ^3.3.2         

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo_garagex.png
    - assets/manual_uso.pdf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_garagex.png"
