name: app_garagex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  shared_preferences: ^2.2.0
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.8

  # MAPAS
  google_maps_flutter: ^2.5.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.0

  # UBICACIÓN
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  permission_handler: ^12.0.0+1

  # RED
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo_garagex.png
